name: CI/CD - Production

on:
  push:
    branches:
      - main

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }}-${{ github.sha }}

  update_helm:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - uses: actions/checkout@v3
      - name: Update Helm values
        run: |
          sed -i "s/tag:.*/tag: ${{ github.ref_name }}-${{ github.sha }}/" helm/values.prod.yaml
      - name: Commit and push Helm values update
        run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git commit -am "[skip ci] Update image tag to ${{ github.ref_name }}-${{ github.sha }}"
            git push
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!            
# IGNORE FOR NOW
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#  deploy_argocd:
#    runs-on: ubuntu-latest
#    needs: update_helm
#    steps:
#      - name: Sync ArgoCD Application
#        run: argocd app sync ${{github.event.repository.name}} --grpc-web

