name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }}-${{ github.sha }}

  update_values:
    name: Update Helm Values for Staging
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
    - uses: actions/checkout@v4
    
    - name: Update Helm values
      run: |
        sed -i "s/tag:.*/tag: ${{ github.ref_name }}-${{ github.sha }}/" helm/values.staging.yaml
        
    - name: Commit and push Helm values update
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -am "[skip ci] Update image tag to ${{ github.ref_name }}-${{ github.sha }}"
        git push

  testing:
    name: Deploy and Test on Kind
    runs-on: ubuntu-latest
    needs: update_values
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Checkout backend repo
      uses: actions/checkout@v4
      with:
        repository: sprysio/simple_spring_boot_backend_test
        path: backend

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Install kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: v0.17.0

    - name: Create Kubernetes cluster
      run: kind create cluster --wait 60s

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy Backend Helm Chart
      run: |
        helm upgrade --install backend-app ./backend/helm --values ./backend/helm/values.staging.yaml
        
    - name: Wait for Backend to be Ready
      run: |
        kubectl rollout status deployment/backend-app -n default

    - name: Deploy Frontend Helm Chart
      run: |
        helm upgrade --install frontend-app ./helm --values helm/values.staging.yaml
        
    - name: Wait for Frontend to be Ready
      run: |
        kubectl rollout status deployment/frontend-app -n default

    - name: Run Integration and E2E Tests
      run: |
        kubectl get pods
        kubectl get services

  rollback:
    name: Rollback on Failure
    runs-on: ubuntu-latest
    needs: testing
    if: failure()
    steps:
    - uses: actions/checkout@v4

    - name: Reset Helm values to previous commit
      run: |
        git checkout HEAD~1 -- helm/values.staging.yaml
        git commit -am "[skip ci] Revert Helm values to previous version"
        git push

